[2022-05-23 20:50:13,872] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_with_python_dependencies_v03.get_sklearn scheduled__2022-04-24T00:00:00+00:00 [queued]>
[2022-05-23 20:50:13,878] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_with_python_dependencies_v03.get_sklearn scheduled__2022-04-24T00:00:00+00:00 [queued]>
[2022-05-23 20:50:13,878] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 20:50:13,878] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-23 20:50:13,878] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 20:50:13,886] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_sklearn> on 2022-04-24 00:00:00+00:00
[2022-05-23 20:50:13,891] {standard_task_runner.py:52} INFO - Started process 677 to run task
[2022-05-23 20:50:13,893] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v03', 'get_sklearn', 'scheduled__2022-04-24T00:00:00+00:00', '--job-id', '1092', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmp8z07gi7l', '--error-file', '/tmp/tmpyplzxvu5']
[2022-05-23 20:50:13,894] {standard_task_runner.py:80} INFO - Job 1092: Subtask get_sklearn
[2022-05-23 20:50:13,927] {task_command.py:369} INFO - Running <TaskInstance: dag_with_python_dependencies_v03.get_sklearn scheduled__2022-04-24T00:00:00+00:00 [running]> on host d1dce7d1386c
[2022-05-23 20:50:13,981] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=gerson
AIRFLOW_CTX_DAG_ID=dag_with_python_dependencies_v03
AIRFLOW_CTX_TASK_ID=get_sklearn
AIRFLOW_CTX_EXECUTION_DATE=2022-04-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-24T00:00:00+00:00
[2022-05-23 20:50:13,982] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 14, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2022-05-23 20:50:13,988] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies_v03, task_id=get_sklearn, execution_date=20220424T000000, start_date=20220523T205013, end_date=20220523T205013
[2022-05-23 20:50:14,018] {standard_task_runner.py:92} ERROR - Failed to execute job 1092 for task get_sklearn (No module named 'sklearn'; 677)
[2022-05-23 20:50:14,065] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-23 20:50:14,092] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
