[2022-05-23 20:50:18,095] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_with_python_dependencies_v03.get_sklearn scheduled__2022-05-10T00:00:00+00:00 [queued]>
[2022-05-23 20:50:18,104] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_with_python_dependencies_v03.get_sklearn scheduled__2022-05-10T00:00:00+00:00 [queued]>
[2022-05-23 20:50:18,104] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 20:50:18,104] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-23 20:50:18,104] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 20:50:18,117] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_sklearn> on 2022-05-10 00:00:00+00:00
[2022-05-23 20:50:18,122] {standard_task_runner.py:52} INFO - Started process 709 to run task
[2022-05-23 20:50:18,126] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v03', 'get_sklearn', 'scheduled__2022-05-10T00:00:00+00:00', '--job-id', '1108', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmp4qvldo97', '--error-file', '/tmp/tmpoa_f8tfm']
[2022-05-23 20:50:18,127] {standard_task_runner.py:80} INFO - Job 1108: Subtask get_sklearn
[2022-05-23 20:50:18,165] {task_command.py:369} INFO - Running <TaskInstance: dag_with_python_dependencies_v03.get_sklearn scheduled__2022-05-10T00:00:00+00:00 [running]> on host d1dce7d1386c
[2022-05-23 20:50:18,211] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=gerson
AIRFLOW_CTX_DAG_ID=dag_with_python_dependencies_v03
AIRFLOW_CTX_TASK_ID=get_sklearn
AIRFLOW_CTX_EXECUTION_DATE=2022-05-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-10T00:00:00+00:00
[2022-05-23 20:50:18,212] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 14, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2022-05-23 20:50:18,218] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies_v03, task_id=get_sklearn, execution_date=20220510T000000, start_date=20220523T205018, end_date=20220523T205018
[2022-05-23 20:50:18,225] {standard_task_runner.py:92} ERROR - Failed to execute job 1108 for task get_sklearn (No module named 'sklearn'; 709)
[2022-05-23 20:50:18,256] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-23 20:50:18,285] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
