[2022-05-23 20:49:19,632] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_with_python_dependencies_v03.get_sklearn scheduled__2021-12-23T00:00:00+00:00 [queued]>
[2022-05-23 20:49:19,639] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_with_python_dependencies_v03.get_sklearn scheduled__2021-12-23T00:00:00+00:00 [queued]>
[2022-05-23 20:49:19,639] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 20:49:19,639] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-23 20:49:19,639] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 20:49:19,650] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_sklearn> on 2021-12-23 00:00:00+00:00
[2022-05-23 20:49:19,655] {standard_task_runner.py:52} INFO - Started process 374 to run task
[2022-05-23 20:49:19,657] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v03', 'get_sklearn', 'scheduled__2021-12-23T00:00:00+00:00', '--job-id', '970', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmp03ob6qxs', '--error-file', '/tmp/tmp6m3pvgt1']
[2022-05-23 20:49:19,658] {standard_task_runner.py:80} INFO - Job 970: Subtask get_sklearn
[2022-05-23 20:49:19,694] {task_command.py:369} INFO - Running <TaskInstance: dag_with_python_dependencies_v03.get_sklearn scheduled__2021-12-23T00:00:00+00:00 [running]> on host d1dce7d1386c
[2022-05-23 20:49:19,743] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=gerson
AIRFLOW_CTX_DAG_ID=dag_with_python_dependencies_v03
AIRFLOW_CTX_TASK_ID=get_sklearn
AIRFLOW_CTX_EXECUTION_DATE=2021-12-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-23T00:00:00+00:00
[2022-05-23 20:49:19,744] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 14, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2022-05-23 20:49:19,749] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies_v03, task_id=get_sklearn, execution_date=20211223T000000, start_date=20220523T204919, end_date=20220523T204919
[2022-05-23 20:49:19,756] {standard_task_runner.py:92} ERROR - Failed to execute job 970 for task get_sklearn (No module named 'sklearn'; 374)
[2022-05-23 20:49:19,788] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-23 20:49:19,806] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
